package:
   name: intake_geopandas
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..
git:
  depth: false

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
    - pandas
  run:
    - intake>=0.2
    - geopandas
    - dask
    - pandas

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - psql -c 'create database travis_test;' -U postgres
    - psql -U postgres -c "create extension postgis"
    - ogr2ogr -f PostgreSQL PG:"dbname='travis_test' user='postgres' port='5432'" tests/data/stations/stations.shp
    - psql -h localhost -p 5432 -U postgres -q -H -c "SELECT * FROM stations"
    - py.test --verbose

about:
  home: https://github.com/informaticslab/intake-geopandas
  license: BSD
  license_file: LICENSE
  summary: |
    Geopandas plugin for Intake
